import source_file

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_cnn_info(object):
    def setupUi(self, cnn_info):
        cnn_info.setObjectName("cnn_info")
        cnn_info.resize(400, 348)
        cnn_info.setSizeGripEnabled(True)
        cnn_info.setWindowIcon(QtGui.QIcon(":/my_pic/ipiu.png"))
        self.gridLayoutWidget = QtWidgets.QWidget(cnn_info)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(60, 40, 231, 181))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 2, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 1, 2, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 2, 2, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout.addWidget(self.lineEdit_4, 3, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 1, 1, 1)
        self.horizontalLayoutWidget = QtWidgets.QWidget(cnn_info)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(60, 230, 231, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ok_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.ok_button.setObjectName("ok_button")
        self.horizontalLayout.addWidget(self.ok_button)
        self.cancel_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.cancel_button.setObjectName("cancel_button")
        self.horizontalLayout.addWidget(self.cancel_button)

        self.retranslateUi(cnn_info)
        QtCore.QMetaObject.connectSlotsByName(cnn_info)

    def retranslateUi(self, cnn_info):
        _translate = QtCore.QCoreApplication.translate
        cnn_info.setWindowTitle(_translate("cnn_info", "CNN model params"))
        self.label_3.setText(_translate("cnn_info", "Param_3:"))
        self.label_4.setText(_translate("cnn_info", "Param_4:"))
        self.label.setText(_translate("cnn_info", "Param_1:"))
        self.label_2.setText(_translate("cnn_info", "Param_2:"))
        self.ok_button.setText(_translate("cnn_info", "OK"))
        self.cancel_button.setText(_translate("cnn_info", "cancel"))


class Ui_fcn_info(object):
    def setupUi(self, fcn_info):
        fcn_info.setObjectName("fcn_info")
        fcn_info.resize(400, 348)
        fcn_info.setSizeGripEnabled(True)
        fcn_info.setWindowIcon(QtGui.QIcon(":/my_pic/ipiu.png"))
        self.gridLayoutWidget = QtWidgets.QWidget(fcn_info)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(60, 40, 231, 181))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 2, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 1, 2, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 2, 2, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout.addWidget(self.lineEdit_4, 3, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 1, 1, 1)
        self.horizontalLayoutWidget = QtWidgets.QWidget(fcn_info)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(60, 230, 231, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ok_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.ok_button.setObjectName("ok_button")
        self.horizontalLayout.addWidget(self.ok_button)
        self.cancel_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.cancel_button.setObjectName("cancel_button")
        self.horizontalLayout.addWidget(self.cancel_button)

        self.retranslateUi(fcn_info)
        QtCore.QMetaObject.connectSlotsByName(fcn_info)

    def retranslateUi(self, cnn_info):
        _translate = QtCore.QCoreApplication.translate
        cnn_info.setWindowTitle(_translate("fcn_info", "FCN model params"))
        self.label_3.setText(_translate("fcn_info", "Param_3:"))
        self.label_4.setText(_translate("fcn_info", "Param_4:"))
        self.label.setText(_translate("fcn_info", "Param_1:"))
        self.label_2.setText(_translate("fcn_info", "Param_2:"))
        self.ok_button.setText(_translate("fcn_info", "OK"))
        self.cancel_button.setText(_translate("fcn_info", "cancel"))


class Ui_gan_info(object):
    def setupUi(self, gnn_info):
        gnn_info.setObjectName("gnn_info")
        gnn_info.resize(400, 348)
        gnn_info.setSizeGripEnabled(True)
        gnn_info.setWindowIcon(QtGui.QIcon(":/my_pic/ipiu.png"))
        self.gridLayoutWidget = QtWidgets.QWidget(gnn_info)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(60, 40, 231, 181))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 1, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 2, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 1, 2, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 2, 2, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout.addWidget(self.lineEdit_4, 3, 2, 1, 1)

        self.horizontalLayoutWidget = QtWidgets.QWidget(gnn_info)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(60, 230, 231, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ok_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.ok_button.setObjectName("ok_button")
        self.horizontalLayout.addWidget(self.ok_button)
        self.cancel_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.cancel_button.setObjectName("cancel_button")
        self.horizontalLayout.addWidget(self.cancel_button)

        self.retranslateUi(gnn_info)
        QtCore.QMetaObject.connectSlotsByName(gnn_info)

    def retranslateUi(self, cnn_info):
        _translate = QtCore.QCoreApplication.translate
        cnn_info.setWindowTitle(_translate("gnn_info", "GNN model params"))
        self.label_3.setText(_translate("gnn_info", "Param_3:"))
        self.label_4.setText(_translate("gnn_info", "Param_4:"))
        self.label.setText(_translate("gnn_info", "Param_1:"))
        self.label_2.setText(_translate("gnn_info", "Param_2:"))
        self.ok_button.setText(_translate("gnn_info", "OK"))
        self.cancel_button.setText(_translate("gnn_info", "cancel"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    cnn_info = QtWidgets.QDialog()
    ui_cnn = Ui_cnn_info()
    ui_cnn.setupUi(cnn_info)
    cnn_info.show()
    sys.exit(app.exec_())
